services:
  postgres:
    image: postgres:17.4
    restart: always
    ports:
      - "127.0.0.1:5434:5432"  # Example: host 5434 to container 5432

    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # - POSTGRES_DB=${POSTGRES_DB:-app_db}
      # Please provide your own password.
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - rails-vue3

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      # DATABASE_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    # command: ["bin/rails", "db:migrate", "&&", "bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - rails-vue3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - rails-vue3

volumes:
  postgres_data:

networks:
  rails-vue3:
    driver: bridge